_Run without modifications (helper functions)_:

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from IPython.display import Markdown #, IFrame
# for presentations:
#display(HTML("<style>.container { width:100% !important; }</style>"))

import numpy as np
import pandas as pd
#pd.set_option("display.max_colwidth", 200)
import matplotlib as mpl
from matplotlib import pyplot as plt
plt.ion()
plt.style.use('seaborn-v0_8-muted')
from pprint import pprint as ptp

import sys
from pathlib import Path
print('Python ver: {}\nPython env: {}'.format(sys.version, Path(sys.prefix).name))
print('Currrent dir: {}\n'.format(Path.cwd()))


def add_to_sys_path(this_path, up=False):
    """
    Prepend this_path to sys.path.
    If up=True, path refers to parent folder (1 level up).
    """

    if up:
        newp = str(Path(this_path).parent)
    else:
        newp = str(Path(this_path))
    if newp not in sys.path:
        sys.path.insert(1, newp)
        print('Path added to sys.path: {}'.format(newp))


def fdir(obj, start_with_str='_', exclude=True):
    """Filtered dir() for method discovery."""
    return [d for d in dir(obj) if not d.startswith(start_with_str) == exclude]

def despine(which=['top','right']):
    """which ([str])): 'left','top','right','bottom'."""

    ax = plt.gca()
    for side in which:
        ax.spines[side].set_visible(False)
    return

def md_width_comment(w:int=120) -> str:
    """Width guide for composing md documents."""
    return f"<!-- dotted line width = {w}\n{'.'*w}-->"


# autoreload extension
%load_ext autoreload
%autoreload 2

Python ver: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
Python env: mce
Currrent dir: /home/cat/projects/MCCE_Benchmarking/notebooks

In [2]:
add_to_sys_path(Path.cwd(), up=True)

Path added to sys.path: /home/cat/projects/MCCE_Benchmarking

---
---

In [ ]:
from mcce_benchmark import BENCH, OUT_FILES, ANALYZE_DIR
from mcce_benchmark import USER_PRFX, USER_ENV, CONDA_PATH
from mcce_benchmark import Pathok
from mcce_benchmark import pkanalysis

#print(BENCH)
print(f"{USER_PRFX = }\n{USER_ENV = }\n{CONDA_PATH = }")

In [ ]:
for fp in OUT_FILES:
    print(fp.name, fp.value)

---
# Use ~/projects/bench_tests/all_pdbs as bdir

In [3]:
here = Path.cwd()
here

PosixPath('/home/cat/projects/MCCE_Benchmarking/notebooks')

In [4]:
bdir = Path("../../bench_tests/all_pdbs").resolve()
bdir
benchmarks_dir = Pathok(bdir)
print(f"{benchmarks_dir = }")

pdbs = Pathok(benchmarks_dir.joinpath(BENCH.CLEAN_PDBS))
print(f"{pdbs = }")

book_fp = pdbs.joinpath(BENCH.Q_BOOK)

PosixPath('/home/cat/projects/bench_tests/all_pdbs')

benchmarks_dir = PosixPath('/home/cat/projects/bench_tests/all_pdbs')
pdbs = PosixPath('/home/cat/projects/bench_tests/all_pdbs/clean_pdbs')

### Q: can a all_pkas.out be loaded into df? YES!!

In [14]:
allout_df = pkanalysis.all_pkas_df(benchmarks_dir)  #titr_type='ph' : default
allout_df.shape
allout_df.info()

(6064, 15)

<class 'pandas.core.frame.DataFrame'>
Index: 6064 entries, 135L to 9RNT
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   resid@pH   6064 non-null   object
 1   pKa/Em     6064 non-null   float64
 2   n(slope)   4839 non-null   float64
 3   1000*chi2  4839 non-null   float64
 4   vdw0       6064 non-null   float64
 5   vdw1       6064 non-null   float64
 6   tors       6064 non-null   float64
 7   ebkb       6064 non-null   float64
 8   dsol       6064 non-null   float64
 9   offset     6064 non-null   float64
 10  pHpK0      6064 non-null   float64
 11  EhEm0      6064 non-null   float64
 12  -TS        6064 non-null   float64
 13  residues   6064 non-null   float64
 14  total      6064 non-null   float64
dtypes: float64(14), object(1)
memory usage: 758.0+ KB

In [9]:
allout_df.head()
allout_df.tail()

,resid@pH,pKa/Em,n(slope),1000*chi2,vdw0,vdw1,tors,ebkb,dsol,offset,pHpK0,EhEm0,-TS,residues,total
PDB,,,,,,,,,,,,,,,
135L,NTR+A0001_,3.012,0.896,0.015,-0.00,-0.01,-0.26,0.61,4.75,-0.95,-4.99,0.0,0.00,0.85,0.01
135L,LYS+A0001_,11.455,0.974,0.028,-0.00,-0.00,0.00,0.22,1.37,0.29,1.06,0.0,0.00,-2.94,-0.00
135L,TYR-A0003_,8888.000,NaN,NaN,0.00,0.00,0.00,1.80,3.38,-0.37,-3.80,0.0,0.03,2.38,3.42
135L,ARG+A0005_,12.485,0.828,0.082,-0.01,-0.00,0.00,-0.60,0.80,0.00,-0.02,0.0,0.14,-0.16,0.15
135L,GLU-A0007_,2.886,0.883,0.066,-0.01,0.00,-0.23,-0.91,1.70,-0.22,1.86,0.0,0.17,-2.19,0.18

,resid@pH,pKa/Em,n(slope),1000*chi2,vdw0,vdw1,tors,ebkb,dsol,offset,pHpK0,EhEm0,-TS,residues,total
PDB,,,,,,,,,,,,,,,
9RNT,ARG+A0077_,8888.000,NaN,NaN,-0.00,-0.01,0.00,-1.20,2.32,0.00,1.50,0.0,0.30,-9.36,-6.45
9RNT,GLU-A0082_,0.886,1.002,0.192,-0.02,0.00,-0.24,-0.41,2.08,-0.22,3.86,0.0,0.30,-4.55,0.81
9RNT,HIS+A0092_,7.567,0.986,0.162,-0.00,-0.00,0.00,-1.12,1.66,-0.73,0.59,0.0,0.00,-0.40,-0.01
9RNT,GLU-A0102_,5.469,0.856,0.844,-0.02,0.01,-0.11,-0.50,0.86,-0.22,-0.72,0.0,0.59,0.72,0.60
9RNT,CTR-A0104_,4.252,0.856,0.021,0.01,0.02,-0.11,-1.10,1.63,0.00,-0.50,0.0,0.39,0.05,0.40

## Out of bound values? +/-8888: out of titration bounds; 9999: curve too sharp

In [12]:
msk = pkanalysis.get_oob_mask(allout_df)  #(abs(allout_df["pKa/Em"]) == 8888.) | (allout_df["pKa/Em"] == 9999.)
oob_df = allout_df[msk]
n_oob = oob_df.shape[0]
n_oob
oob_df.head()

1225

,resid@pH,pKa/Em,n(slope),1000*chi2,vdw0,vdw1,tors,ebkb,dsol,offset,pHpK0,EhEm0,-TS,residues,total
PDB,,,,,,,,,,,,,,,
135L,TYR-A0003_,8888.0,NaN,NaN,0.00,0.0,0.00,1.80,3.38,-0.37,-3.8,0.0,0.03,2.38,3.42
135L,ARG+A0021_,8888.0,NaN,NaN,-0.01,-0.0,0.00,-1.49,0.69,0.00,1.5,0.0,0.22,-1.29,-0.38
135L,TYR-A0053_,8888.0,NaN,NaN,0.00,0.0,-0.01,-1.66,3.55,-0.37,-3.8,0.0,0.34,8.32,6.38
135L,ARG+A0068_,8888.0,NaN,NaN,-0.01,-0.0,0.00,0.28,0.04,0.00,1.5,0.0,0.34,-1.84,0.31
1A2P,TYR-A0013_,8888.0,NaN,NaN,0.00,0.0,0.00,-0.43,2.94,-0.37,-3.8,0.0,0.30,3.04,1.67

In [15]:
## Reset allout_df: no oob:
allout_df.shape
allout_df = allout_df[~msk]
allout_df.shape

(6064, 15)

(4839, 15)

### Other way to load a pkout file into a df: pkanalysis.pkout_df(pko_fp:str, collated=True)

In [110]:
allout = benchmarks_dir.joinpath(OUT_FILES.ALL_PKAS_FILE.value)
allout.exists()

True

In [112]:
allout_df2 = pkanalysis.pkout_df(allout, collated=True)  # False is default
allout_df2.head()

,resid@pH,pKa/Em,n(slope),1000*chi2,vdw0,vdw1,tors,ebkb,dsol,offset,pHpK0,EhEm0,-TS,residues,total
PDB,,,,,,,,,,,,,,,
135L,NTR+A0001_,3.012,0.896,0.015,-0.00,-0.01,-0.26,0.61,4.75,-0.95,-4.99,0.0,0.00,0.85,0.01
135L,LYS+A0001_,11.455,0.974,0.028,-0.00,-0.00,0.00,0.22,1.37,0.29,1.06,0.0,0.00,-2.94,-0.00
135L,TYR-A0003_,NaN,NaN,NaN,0.00,0.00,0.00,1.80,3.38,-0.37,-3.80,0.0,0.03,2.38,3.42
135L,ARG+A0005_,12.485,0.828,0.082,-0.01,-0.00,0.00,-0.60,0.80,0.00,-0.02,0.0,0.14,-0.16,0.15
135L,GLU-A0007_,2.886,0.883,0.066,-0.01,0.00,-0.23,-0.91,1.70,-0.22,1.86,0.0,0.17,-2.19,0.18

### Filtering allout_df

# Filter allout:

bca_df = allout_df.loc["2BCA"]
bca_df.shape
bca_df.head(3)

bca_df.columns
# cols for job pka:
c_resid, c_pka =  bca_df.columns[:2]
c_resid, c_pka

In [13]:
benchmarks_dir

PosixPath('/home/cat/projects/bench_tests/all_pdbs')

### Other way: load one pk.out file:

In [34]:
onepk = benchmarks_dir.joinpath(BENCH.CLEAN_PDBS, "2BCA", "pK.out")
one_dfo = pkanalysis.pkout_df(onepk)  # collated=False: default
one_dfo.head(3)

,pKa/Em,n(slope),1000*chi2,vdw0,vdw1,tors,ebkb,dsol,offset,pHpK0,EhEm0,-TS,residues,total
pH,,,,,,,,,,,,,,
NTR+A0001_,8.385,0.985,0.008,-0.00,-0.0,-0.26,0.91,0.45,-0.95,0.38,0.0,0.00,-0.54,-0.01
LYS+A0001_,12.357,0.943,0.012,-0.00,-0.0,0.00,0.25,0.75,0.29,1.96,0.0,0.00,-3.24,0.00
GLU-A0004_,3.994,0.874,0.080,-0.01,0.0,-0.17,-0.42,0.12,-0.22,0.76,0.0,0.57,-0.04,0.57

## Out of bound values? +/-8888: out of titration bounds; 9999: curve too sharp

In [39]:
msk = pkanalysis.get_oob_mask(one_dfo)
one_dfo[msk]

,pKa/Em,n(slope),1000*chi2,vdw0,vdw1,tors,ebkb,dsol,offset,pHpK0,EhEm0,-TS,residues,total
pH,,,,,,,,,,,,,,
TYR-A0013_,8888.0,NaN,NaN,0.0,0.0,-0.0,-0.25,2.46,-0.37,-3.8,0.0,0.15,2.36,0.56

---
---
---